alias l='ls -lh'
alias c='git add . && git came'
alias d='git dh'
alias m='git add . && git commit -m'
alias s='git st'
alias b='npm run build'
alias t='npm run typecheck'
alias g='git tree'
alias fsl='sl'
alias lt='npm run lint --fix'
alias ci='npm run ci'

